sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
install: "pip install uranium; mkdir -p venv; cd venv && uranium"
script: "py.test uranium/newtests --cov uranium --cov-config coverage.cfg"